### ISSUE TITLE
multiline strings in package image are interpreted as template

### ISSUE THREAD

**Issue by jan--f** [package-operator/package-operator#101]
I have a package that includes a `PrometheusRule` resource. Here is an excerpt:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: observability-operator-rules
    app.kubernetes.io/part-of: observability-operator
    prometheus: k8s
    role: alert-rules
  name: observability-operator-rules
spec:
  groups:
  - name: observability-operator.rules
    rules:
    - alert: Observability Operator controller reconcile errors
      annotations:
        description: |
          Observability Operator controller - {{ $labels.controller }} fails to reconcile.
          Inspect the observability-operator log for potential root causes.
        summary: Observability Operator controller - {{ $labels.controller }} fails to reconcile
      expr: |
        increase(controller_runtime_reconcile_errors_total{job="observability-operator"}[15m]) > 0
      for: 15m
      labels:
        severity: warning
```

It seems like package-operator tries to interpret the multiline description as a template. This results in:

```
Status:
  Conditions:
    Last Transition Time:  2022-11-29T14:53:42Z
    Message:               Unpack job in progress
    Observed Generation:   1
    Reason:                Unpacking
    Status:                False
    Type:                  Unpacked
    Last Transition Time:  2022-11-29T14:53:44Z
    Message:               parsing yaml from /package/operator/resources.yaml: parsing template from yaml document at index 6: template: yaml#6:20: undefined variable "$labels"
    Observed Generation:   1
    Reason:                LoadError
    Status:                True
    Type:                  Invalid
  Phase:                   Invalid
```
