### ISSUE TITLE
Allow referencing a configmap directly as a (Cluster)Package config (bypassing `ObjectTemplate`s)

### ISSUE THREAD

**Issue by jbpratt** [package-operator/package-operator#755]
I'd like to propose the idea of being able to bypass the control that `ObjectTemplate`s provide in the sources section, and reference a `ConfigMap` directly to splat the values in as parameters to be templated. In our case, we don't need the added complexities of managing each field within the configmap but instead just want to directly apply them as is.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: integration
data:
  namespace: production-namespace
  image: quay.io/yourusername/wizard:stable
  app: wizard
```

```
apiVersion: package-operator.run/v1alpha1
kind: ClusterPackage
metadata:
  name: wizard-bundle
spec:
  image: quay.io/yourusername/wizard-bundle:latest
  configMapRef:
    name: myapp-config
    namespace: integration
```

which would effectively resolve to

```
apiVersion: package-operator.run/v1alpha1
kind: ClusterPackage
metadata:
  name: wizard-bundle
spec:
  image: quay,io/yourusername/wizard-bundle:latest
  config:
    namespace: production-namespace
    image: quay.io/yourusername/wizard:stable
    app: wizard
```
